[package]
name = "xiaomi-sensor-datadog-export"
version = "0.1.0"
authors = ["Jérémie Drouet <jeremie.drouet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluez = "^0.3"
bytes = "^1.0"
env_logger = "0.8"
log = "0.4"
reqwest = { version = "0.11.1", features = ["json"] }
serde_json = "1.0"
tokio = { version = "^1.2", features = ["full"] }
datadog-client = { version = "^0.2" }
