name: main

on: [push]

jobs:
  code-checking:
    runs-on: ubuntu-latest

    concurrency: 
      group: ${{ github.ref }}-code-checking
      cancel-in-progress: true

    steps:
      - name: install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ libclang-11-dev libbluetooth-dev

      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt,clippy

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: run lint
        run: cargo fmt --check

      - name: run check
        run: cargo check --all-features --tests

      - name: run clippy
        run: cargo clippy --all-targets --all-features --tests
